import { Cinzel, Urbanist } from "next/font/google";

import { ThemeProvider } from "@mui/material";

import Header from "@/components/layout/Header";

import theme from "@/theme/theme";

import "@/styles/globals.css";

const cinzel = Cinzel({ variable: "--font-cinzel-serif", subsets: ["latin"] });

const urbanist = Urbanist({
  variable: "--font-urbanist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${cinzel.variable} ${urbanist.variable}`}>
        <ThemeProvider theme={theme}>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
